// LOCALHOST
### Get all products
GET http://localhost:3000/products


### Get product by id
GET http://localhost:3000/products/678f4cbbb0f81a775e0f57c5


### Create product
POST http://localhost:3000/products HTTP/1.1
content-type: application/json

{
  "title":"Product 3",
  "price":"105.35",
  "description":"Description product 2",
  "category":"Men clothing",
  "image":"https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
  "rating":5
}


### PUT product
PUT http://localhost:3000/products/67920efe9062ab64e87e689a HTTP/1.1
content-type: application/json

{
  "title":"Product 3",
  "price":"105.50",
  "description":"Description product 3",
  "category":"Men clothing",
  "image":"https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
  "rating":4
}


### DELETE product
DELETE http://localhost:3000/products/67920efe9062ab64e87e689a HTTP/1.1

